init.d/cman: unfence local node
Run fence_node -U after cman_tool join.  This does nothing unless
unfencing is defined for the local node.  If unfencing is defined
and the unfencing fails, it causes init.d/cman to fail.

Signed-off-by: David Teigland <teigland@redhat.com>

diff --git a/cman/init.d/cman.in b/cman/init.d/cman.in
--- a/cman/init.d/cman.in
+++ b/cman/init.d/cman.in
@@ -204,6 +204,25 @@ start_cman()
     return 0
 }
 
+unfence_self()
+{
+    fence_node -U > /dev/null 2>&1
+    error=$?
+
+    if [ $error -eq 0 ]
+    then
+        echo "   Unfencing self... done"
+        return 0
+    else
+        if [ $error -eq 1 ]
+        then
+            echo "   Unfencing self... failed"
+            return 1
+        else
+            return 0
+        fi
+    fi
+}
 
 start_qdiskd()
 {
@@ -464,6 +483,12 @@ start()
     else
 	echo "failed"
 	return 1
+    fi
+
+    unfence_self
+    if [ $? -eq 1 ]
+    then
+        return 1
     fi
 
     start_qdiskd
